[package]
name = "tilemap2src"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image="0.24"
clap={version="4.1", features=["derive"]}
serde_yaml="0.9"
serde = { version = "1.0", features = ["derive"] }
