// Autogenerated by tilemap2src

// -- conveyor
pub const TILEDATA_conveyor: [u8; 7]= [101,66,0,32,32,101,64,];
pub const TILE_conveyor_WIDTH: u8 = 5;
pub const TILE_conveyor_HEIGHT: u8 = 5;
pub const TILE_conveyor_BPP: u8 = 2;


// -- drill
pub const TILEDATA_drill: [u8; 7]= [76,67,15,188,252,76,64,];
pub const TILE_drill_WIDTH: u8 = 5;
pub const TILE_drill_HEIGHT: u8 = 5;
pub const TILE_drill_BPP: u8 = 2;


// -- furnace
pub const TILEDATA_furnace: [u8; 7]= [191,187,191,191,187,191,128,];
pub const TILE_furnace_WIDTH: u8 = 5;
pub const TILE_furnace_HEIGHT: u8 = 5;
pub const TILE_furnace_BPP: u8 = 2;


// -- grinder
pub const TILEDATA_grinder: [u8; 7]= [255,215,85,149,117,255,192,];
pub const TILE_grinder_WIDTH: u8 = 5;
pub const TILE_grinder_HEIGHT: u8 = 5;
pub const TILE_grinder_BPP: u8 = 2;


// -- glass
pub const TILEDATA_glass: [u8; 7]= [85,90,150,165,169,85,64,];
pub const TILE_glass_WIDTH: u8 = 5;
pub const TILE_glass_HEIGHT: u8 = 5;
pub const TILE_glass_BPP: u8 = 2;


// -- plate
pub const TILEDATA_plate: [u8; 7]= [89,95,219,249,253,89,64,];
pub const TILE_plate_WIDTH: u8 = 5;
pub const TILE_plate_HEIGHT: u8 = 5;
pub const TILE_plate_BPP: u8 = 2;


// -- wire
pub const TILEDATA_wire: [u8; 7]= [95,93,117,215,93,125,64,];
pub const TILE_wire_WIDTH: u8 = 5;
pub const TILE_wire_HEIGHT: u8 = 5;
pub const TILE_wire_BPP: u8 = 2;


// -- box
pub const TILEDATA_box: [u8; 7]= [255,241,61,31,19,255,192,];
pub const TILE_box_WIDTH: u8 = 5;
pub const TILE_box_HEIGHT: u8 = 5;
pub const TILE_box_BPP: u8 = 2;


// -- generator
pub const TILEDATA_generator: [u8; 7]= [2,130,130,168,40,40,0,];
pub const TILE_generator_WIDTH: u8 = 5;
pub const TILE_generator_HEIGHT: u8 = 5;
pub const TILE_generator_BPP: u8 = 2;


// -- depot
pub const TILEDATA_depot: [u8; 25]= [85,85,84,0,1,79,192,20,195,1,76,48,20,195,1,76,48,20,252,49,64,0,21,85,85,];
pub const TILE_depot_WIDTH: u8 = 10;
pub const TILE_depot_HEIGHT: u8 = 10;
pub const TILE_depot_BPP: u8 = 2;


// -- rocket
pub const TILEDATA_rocket: [u8; 25]= [85,245,84,58,193,67,172,20,250,241,119,173,215,122,221,119,253,215,112,221,127,15,213,85,85,];
pub const TILE_rocket_WIDTH: u8 = 10;
pub const TILE_rocket_HEIGHT: u8 = 10;
pub const TILE_rocket_BPP: u8 = 2;


